import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Activity, Building2, CalendarDays, Check, ChevronRight, ClipboardPlus, Clock3, FileCheck2, LayoutDashboard, Menu, Plus, Search, Stethoscope, UserRound, UsersRound, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { lookupCnpj } from "@/lib/cnpj.functions";
import { UserManagement } from "@/components/UserManagement";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type Section = "dashboard" | "companies" | "employees" | "exams" | "schedule" | "users";
type Company = { id:string; cnpj:string; legal_name:string; trade_name:string|null; status:"pending"|"approved"|"rejected"|"inactive"; city:string|null; state:string|null; registration_status:string|null; created_at:string };
type Employee = { id:string; company_id:string; full_name:string; cpf:string; rg:string; birthplace:string; nationality:string; birth_date:string; sex:string; job_title:string; admission_date:string; workplace:string; is_active:boolean };
type Exam = { id:string; category:"clinical"|"complementary"; name_pt:string; name_en:string; duration_minutes:number; is_active:boolean };
type Appointment = { id:string; company_id:string; employee_id:string; assessment_type:string; starts_at:string; ends_at:string; location:string; status:"scheduled"|"confirmed"|"completed"|"cancelled"; employees?: { full_name:string } | null };
type Profile = { id:string; company_id:string|null; full_name:string; preferred_language:string };

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [
    { title: "Painel | MedAgenda Ocupacional" }, { name: "description", content: "Gestão de empresas, funcionários e exames ocupacionais." },
    { property: "og:title", content: "Painel | MedAgenda Ocupacional" }, { property: "og:description", content: "Gestão de empresas, funcionários e exames ocupacionais." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ]}),
  component: DashboardPage,
});

function DashboardPage() {
  const { language, setLanguage, t } = useI18n(); const navigate = useNavigate();
  const [section,setSection]=useState<Section>("dashboard"); const [mobile,setMobile]=useState(false); const [loading,setLoading]=useState(true);
  const [profile,setProfile]=useState<Profile|null>(null); const [isMaster,setIsMaster]=useState(false); const [companies,setCompanies]=useState<Company[]>([]);
  const [employees,setEmployees]=useState<Employee[]>([]); const [exams,setExams]=useState<Exam[]>([]); const [appointments,setAppointments]=useState<Appointment[]>([]);
  const [dialog,setDialog]=useState<"company"|"employee"|"exam"|"appointment"|"join"|null>(null); const [query,setQuery]=useState(""); const [notice,setNotice]=useState("");

  async function load() {
    setLoading(true); const { data:userData }=await supabase.auth.getUser(); const user=userData.user; if(!user)return;
    let { data:p }=await supabase.from("profiles").select("id,company_id,full_name,preferred_language").eq("id",user.id).maybeSingle();
    if(!p){ await supabase.rpc("initialize_profile",{_full_name:String(user.user_metadata?.["full_name"] ?? user.email?.split("@")[0] ?? "Usuário"),_language:language}); const result=await supabase.from("profiles").select("id,company_id,full_name,preferred_language").eq("id",user.id).single(); p=result.data; }
    if(p){setProfile(p); if(p.preferred_language==="pt"||p.preferred_language==="en")setLanguage(p.preferred_language);}
    const [{data:roles},{data:companyRows},{data:employeeRows},{data:examRows},{data:appointmentRows}]=await Promise.all([
      supabase.from("user_roles").select("role").eq("user_id",user.id), supabase.from("companies").select("id,cnpj,legal_name,trade_name,status,city,state,registration_status,created_at").order("created_at",{ascending:false}),
      supabase.from("employees").select("*").order("full_name"), supabase.from("exams").select("id,category,name_pt,name_en,duration_minutes,is_active").order("category").order("name_pt"),
      supabase.from("appointments").select("id,company_id,employee_id,assessment_type,starts_at,ends_at,location,status,employees(full_name)").order("starts_at"),
    ]);
    setIsMaster(Boolean(roles?.some(r=>r.role==="master"))); setCompanies((companyRows??[]) as Company[]); setEmployees((employeeRows??[]) as Employee[]); setExams((examRows??[]) as Exam[]); setAppointments((appointmentRows??[]) as Appointment[]); setLoading(false);
  }
  useEffect(()=>{void load();},[]);
  async function signOut(){await supabase.auth.signOut();await navigate({to:"/auth",replace:true});}
  const filteredEmployees=employees.filter(e=>`${e.full_name} ${e.cpf} ${e.job_title} ${e.workplace}`.toLowerCase().includes(query.toLowerCase()));
  const today=new Date().toISOString().slice(0,10); const todayCount=appointments.filter(a=>a.starts_at.slice(0,10)===today && a.status!=="cancelled").length;
  const weekCount=appointments.filter(a=>new Date(a.starts_at).getTime()>=Date.now()&&new Date(a.starts_at).getTime()<Date.now()+604800000&&a.status!=="cancelled").length;
  const labels=language==="pt"?{hello:"Olá",companiesDesc:"Cadastros e validações de CNPJ",employeesDesc:"Dados ocupacionais e vínculos",examsDesc:"Catálogo clínico e complementar",scheduleDesc:"Atendimentos e status",join:"Vincular empresa",noCompany:"Sua conta ainda não está vinculada a uma empresa.",review:"Revisar",all:"Todos",clinical:"Clínicos",complementary:"Complementares"}:{hello:"Hello",companiesDesc:"CNPJ registrations and reviews",employeesDesc:"Occupational data and employment",examsDesc:"Clinical and complementary catalog",scheduleDesc:"Appointments and statuses",join:"Join company",noCompany:"Your account is not linked to a company yet.",review:"Review",all:"All",clinical:"Clinical",complementary:"Complementary"};
  const nav=[{id:"dashboard",label:t("dashboard"),icon:LayoutDashboard},{id:"companies",label:t("companies"),icon:Building2},{id:"employees",label:t("employees"),icon:UsersRound},{id:"exams",label:t("exams"),icon:Stethoscope},{id:"schedule",label:t("schedule"),icon:CalendarDays},{id:"users",label:language==="pt"?"Usuários":"Users",icon:UserRound}] as const;

  return <div className="min-h-screen bg-background text-foreground"><aside className={`fixed inset-y-0 left-0 z-40 w-64 border-r border-sidebar-border bg-sidebar transition-transform lg:translate-x-0 ${mobile?"translate-x-0":"-translate-x-full"}`}>
    <div className="flex h-18 items-center justify-between border-b border-sidebar-border px-5"><button className="flex items-center gap-3" onClick={()=>setSection("dashboard")}><span className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><Activity className="size-5"/></span><span className="text-lg font-semibold">MedAgenda</span></button><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(false)}><X/></Button></div>
    <nav className="space-y-1 p-3">{nav.filter(item=>isMaster||(item.id!=="companies"&&item.id!=="users")).map(item=><Button key={item.id} variant={section===item.id?"secondary":"ghost"} className="w-full justify-start" onClick={()=>{setSection(item.id);setMobile(false)}}><item.icon/>{item.label}</Button>)}</nav>
    <div className="absolute inset-x-3 bottom-3 rounded-md border bg-background p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-md bg-accent"><UserRound className="size-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{profile?.full_name??"—"}</p><p className="text-xs text-muted-foreground">{isMaster?"Master":"Empresa"}</p></div></div><Button variant="ghost" size="sm" className="mt-2 w-full justify-start text-muted-foreground" onClick={signOut}>{t("signOut")}</Button></div>
  </aside>{mobile&&<button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" aria-label="Fechar menu" onClick={()=>setMobile(false)}/>}<div className="lg:pl-64">
    <header className="sticky top-0 z-20 flex h-18 items-center gap-3 border-b bg-background/95 px-4 backdrop-blur sm:px-6"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></Button><div className="flex-1"><p className="text-sm text-muted-foreground">MedAgenda Ocupacional</p><h1 className="font-semibold">{nav.find(n=>n.id===section)?.label}</h1></div><div className="flex rounded-md border p-0.5"><Button size="sm" variant={language==="pt"?"secondary":"ghost"} onClick={()=>setLanguage("pt")}>PT</Button><Button size="sm" variant={language==="en"?"secondary":"ghost"} onClick={()=>setLanguage("en")}>EN</Button></div></header>
    <main className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8">{notice&&<div className="mb-5 flex items-center justify-between rounded-md border border-primary/20 bg-accent p-3 text-sm"><span>{notice}</span><Button variant="ghost" size="icon" onClick={()=>setNotice("")}><X/></Button></div>}
      {loading?<Loading/>:section==="dashboard"?<><div className="mb-8"><h2 className="text-2xl font-semibold">{labels.hello}, {profile?.full_name.split(" ")[0]}.</h2><p className="mt-1 text-muted-foreground">{t("subtitle")}</p></div>{!isMaster&&!profile?.company_id&&<div className="mb-6 flex flex-col justify-between gap-4 border-l-4 border-highlight bg-card p-5 sm:flex-row sm:items-center"><div><p className="font-semibold">{labels.noCompany}</p><p className="text-sm text-muted-foreground">Use o código fornecido pelo administrador.</p></div><Button onClick={()=>setDialog("join")}>{labels.join}<ChevronRight/></Button></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Clock3} label={t("today")} value={todayCount}/><Metric icon={CalendarDays} label={t("thisWeek")} value={weekCount}/><Metric icon={UsersRound} label={t("totalEmployees")} value={employees.filter(e=>e.is_active).length}/><Metric icon={Building2} label={t("pendingCompanies")} value={companies.filter(c=>c.status==="pending").length}/></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Panel title={t("upcoming")} action={<Button size="sm" onClick={()=>setDialog("appointment")}><Plus/>{t("newAppointment")}</Button>}><AppointmentList rows={appointments.slice(0,6)} language={language}/></Panel><Panel title={language==="pt"?"Ações rápidas":"Quick actions"}><div className="grid gap-3"><Quick icon={UsersRound} title={t("newEmployee")} onClick={()=>setDialog("employee")}/>{isMaster&&<Quick icon={Building2} title={t("newCompany")} onClick={()=>setDialog("company")}/>}<Quick icon={ClipboardPlus} title={t("newAppointment")} onClick={()=>setDialog("appointment")}/></div></Panel></div></>
      :section==="companies"?<Section title={t("companies")} subtitle={labels.companiesDesc} action={<Button onClick={()=>setDialog("company")}><Plus/>{t("newCompany")}</Button>}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{companies.map(c=><div key={c.id} className="rounded-md border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{c.trade_name||c.legal_name}</p><p className="mt-1 text-xs text-muted-foreground">{formatCnpj(c.cnpj)}</p></div><Status status={c.status} t={t}/></div><p className="mt-5 text-sm text-muted-foreground">{c.city&&c.state?`${c.city} · ${c.state}`:"Localização não informada"}</p><p className="mt-2 text-xs text-muted-foreground">Receita Federal: {c.registration_status||"—"}</p>{c.status==="pending"&&<div className="mt-5 flex gap-2"><Button size="sm" onClick={()=>void reviewCompany(c.id,"approved")}><Check/>Aprovar</Button><Button size="sm" variant="outline" onClick={()=>void reviewCompany(c.id,"rejected")}>Rejeitar</Button></div>}</div>)}</div></Section>
      :section==="employees"?<Section title={t("employees")} subtitle={labels.employeesDesc} action={<Button onClick={()=>setDialog("employee")} disabled={!isMaster&&!profile?.company_id}><Plus/>{t("newEmployee")}</Button>}><SearchBox value={query} setValue={setQuery} placeholder={`${t("search")}...`}/><div className="mt-4 overflow-hidden rounded-md border bg-card"><div className="grid grid-cols-[1.5fr_1fr_1fr] gap-3 border-b bg-muted/50 px-4 py-3 text-xs font-semibold uppercase text-muted-foreground"><span>Nome / CPF</span><span>Função</span><span>Posto</span></div>{filteredEmployees.map(e=><div key={e.id} className="grid grid-cols-[1.5fr_1fr_1fr] gap-3 border-b px-4 py-4 text-sm last:border-0"><span><b className="block">{e.full_name}</b><small className="text-muted-foreground">{formatCpf(e.cpf)}</small></span><span>{e.job_title}</span><span>{e.workplace}</span></div>)}{!filteredEmployees.length&&<Empty/>}</div></Section>
       :section==="exams"?<Section title={t("exams")} subtitle={labels.examsDesc} action={isMaster?<Button onClick={()=>setDialog("exam")}><Plus/>{t("newExam")}</Button>:undefined}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{exams.map(e=><div key={e.id} className="rounded-md border bg-card p-5"><div className="flex justify-between"><span className="grid size-9 place-items-center rounded-md bg-accent text-primary"><Stethoscope className="size-4"/></span><Badge variant="outline">{e.category==="clinical"?labels.clinical:labels.complementary}</Badge></div><h3 className="mt-5 font-semibold">{language==="pt"?e.name_pt:e.name_en}</h3><p className="mt-2 text-sm text-muted-foreground">{e.duration_minutes} min · {e.is_active?t("active"):t("inactive")}</p></div>)}</div></Section>
       :section==="users"&&isMaster?<UserManagement language={language}/>
       :<Section title={t("schedule")} subtitle={labels.scheduleDesc} action={<Button onClick={()=>setDialog("appointment")} disabled={!employees.length}><Plus/>{t("newAppointment")}</Button>}><div className="mb-5 flex gap-2"><Button size="sm">{language==="pt"?"Lista":"List"}</Button><Button size="sm" variant="outline">{language==="pt"?"Semana":"Week"}</Button></div><div className="overflow-hidden rounded-md border bg-card"><AppointmentList rows={appointments} language={language}/>{!appointments.length&&<Empty/>}</div></Section>}
    </main></div>
    <CompanyDialog open={dialog==="company"} onClose={()=>setDialog(null)} language={language} onSaved={async()=>{setDialog(null);setNotice("Empresa enviada para revisão.");await load()}}/>
    <EmployeeDialog open={dialog==="employee"} onClose={()=>setDialog(null)} language={language} companyId={profile?.company_id??companies.find(c=>c.status==="approved")?.id??null} onSaved={async()=>{setDialog(null);setNotice("Funcionário cadastrado.");await load()}}/>
    <ExamDialog open={dialog==="exam"} onClose={()=>setDialog(null)} onSaved={async()=>{setDialog(null);setNotice("Exame adicionado ao catálogo.");await load()}}/>
    <AppointmentDialog open={dialog==="appointment"} onClose={()=>setDialog(null)} employees={employees} exams={exams} profile={profile} companies={companies} onSaved={async()=>{setDialog(null);setNotice("Agendamento criado.");await load()}}/>
    <JoinDialog open={dialog==="join"} onClose={()=>setDialog(null)} onSaved={async()=>{setDialog(null);setNotice("Empresa vinculada com sucesso.");await load()}}/>
  </div>;

  async function reviewCompany(id:string,status:"approved"|"rejected"){const {data:user}=await supabase.auth.getUser();const {error}=await supabase.from("companies").update({status,reviewed_by:user.user?.id??null,reviewed_at:new Date().toISOString(),rejection_reason:status==="rejected"?"Cadastro requer ajustes":null}).eq("id",id);if(error){setNotice(error.message);return;}if(status==="approved"){const code=`EMP-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const {error:codeError}=await supabase.rpc("create_company_access_code",{_company_id:id,_plain_code:code,_label:"Acesso principal"});setNotice(codeError?"Empresa aprovada, mas não foi possível gerar o código.":`Empresa aprovada. Código de acesso: ${code}`);}else setNotice("Empresa rejeitada.");await load();}
}

function Metric({icon:Icon,label,value}:{icon:typeof Clock3;label:string;value:number}){return <div className="rounded-md border bg-card p-5"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><Icon className="size-5 text-primary"/></div><p className="mt-3 text-3xl font-semibold">{value}</p></div>}
function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="rounded-md border bg-card"><header className="flex items-center justify-between border-b p-5"><h3 className="font-semibold">{title}</h3>{action}</header><div className="p-5">{children}</div></section>}
function Section({title,subtitle,action,children}:{title:string;subtitle:string;action?:ReactNode;children:ReactNode}){return <><header className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-1 text-muted-foreground">{subtitle}</p></div>{action}</header>{children}</>}
function Quick({icon:Icon,title,onClick}:{icon:typeof UsersRound;title:string;onClick:()=>void}){return <Button variant="outline" className="h-auto justify-between p-4" onClick={onClick}><span className="flex items-center gap-3"><Icon className="text-primary"/>{title}</span><ChevronRight/></Button>}
function SearchBox({value,setValue,placeholder}:{value:string;setValue:(v:string)=>void;placeholder:string}){return <div className="relative max-w-md"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder}/></div>}
function Empty(){return <div className="p-10 text-center text-sm text-muted-foreground">Nenhum registro encontrado.</div>}
function Loading(){return <div className="grid min-h-[50vh] place-items-center"><Activity className="size-8 animate-pulse text-primary"/></div>}
function Status({status,t}:{status:Company["status"];t:(k:any)=>string}){const tone=status==="approved"?"bg-success/15 text-success":status==="rejected"?"bg-destructive/10 text-destructive":"bg-warning/15 text-warning";return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{t(status as any)}</span>}
function AppointmentList({rows,language}:{rows:Appointment[];language:"pt"|"en"}){return <div className="divide-y">{rows.map(a=><div key={a.id} className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"><div className="w-14 text-center"><b className="block text-sm">{new Date(a.starts_at).toLocaleTimeString(language==="pt"?"pt-BR":"en",{hour:"2-digit",minute:"2-digit"})}</b><small className="text-muted-foreground">{new Date(a.starts_at).toLocaleDateString(language==="pt"?"pt-BR":"en",{day:"2-digit",month:"short"})}</small></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{a.employees?.full_name??"Funcionário"}</p><p className="truncate text-sm text-muted-foreground">{a.location}</p></div><Badge variant="outline">{a.status}</Badge></div>)}</div>}
function DialogFrame({open,onClose,title,description,children,onSubmit}:{open:boolean;onClose:()=>void;title:string;description:string;children:ReactNode;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><form onSubmit={onSubmit} className="space-y-5">{children}<DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit">Salvar</Button></DialogFooter></form></DialogContent></Dialog>}
function Field({label,name,type="text",required=true,defaultValue}:{label:string;name:string;type?:string;required?:boolean;defaultValue?:string|undefined}){return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} defaultValue={defaultValue} maxLength={160}/></div>}

function CompanyDialog({open,onClose,onSaved,language}:{open:boolean;onClose:()=>void;onSaved:()=>void;language:"pt"|"en"}){type CnpjResult={cnpj:string;legal_name:string;trade_name:string;registration_status:string;cnae_code:string;cnae_description:string;email:string;phone:string;street:string;number:string;complement:string;district:string;city:string;state:string;postal_code:string};const [found,setFound]=useState<CnpjResult|null>(null);const [error,setError]=useState("");const [checking,setChecking]=useState(false);async function check(){const el=document.querySelector<HTMLInputElement>('input[name="cnpj"]');const cnpj=(el?.value??"").replace(/\D/g,"");if(cnpj.length!==14){setError("Informe os 14 dígitos do CNPJ.");return;}setChecking(true);const result=await lookupCnpj({data:{cnpj}});setChecking(false);if(!result.ok){setError(result.message);return;}setFound(result.company);setError("");}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!found)return;const {data:user}=await supabase.auth.getUser();if(!user.user)return;const {error:saveError}=await supabase.from("companies").insert({...found,status:"pending",created_by:user.user.id});if(saveError)setError(saveError.message);else onSaved();}
 return <DialogFrame open={open} onClose={onClose} onSubmit={submit} title={language==="pt"?"Cadastrar empresa":"Register company"} description="Consulte o CNPJ e revise os dados oficiais antes de enviar."><div className="flex gap-2"><div className="flex-1"><Field label="CNPJ" name="cnpj"/></div><Button type="button" variant="outline" className="mt-8" onClick={check} disabled={checking}>{checking?"Consultando...":"Consultar"}</Button></div>{error&&<p className="text-sm text-destructive">{error}</p>}{found&&<div className="grid gap-4 rounded-md border bg-muted/30 p-4 sm:grid-cols-2"><Field label="Razão social" name="legal_name" defaultValue={found.legal_name}/><Field label="Nome fantasia" name="trade_name" required={false} defaultValue={found.trade_name}/><Field label="Situação cadastral" name="status" defaultValue={found.registration_status}/><Field label="Cidade / UF" name="city" defaultValue={`${found.city} / ${found.state}`}/></div>}</DialogFrame>}
function EmployeeDialog({open,onClose,onSaved,companyId,language}:{open:boolean;onClose:()=>void;onSaved:()=>void;companyId:string|null;language:"pt"|"en"}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!companyId){setError("Selecione ou vincule uma empresa aprovada.");return;}const f=new FormData(e.currentTarget);const {data:user}=await supabase.auth.getUser();const row={company_id:companyId,full_name:String(f.get("full_name")),cpf:String(f.get("cpf")).replace(/\D/g,""),rg:String(f.get("rg")),birthplace:String(f.get("birthplace")),nationality:String(f.get("nationality")),birth_date:String(f.get("birth_date")),sex:String(f.get("sex")),job_title:String(f.get("job_title")),admission_date:String(f.get("admission_date")),workplace:String(f.get("workplace")),created_by:user.user?.id??""};const {error:saveError}=await supabase.from("employees").insert(row);if(saveError)setError(saveError.message);else onSaved();}
 return <DialogFrame open={open} onClose={onClose} onSubmit={submit} title={language==="pt"?"Novo funcionário":"New employee"} description="Dados pessoais e vínculo ocupacional."><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo" name="full_name"/><Field label="CPF" name="cpf"/><Field label="RG" name="rg"/><Field label="Naturalidade" name="birthplace"/><Field label="Nacionalidade" name="nationality"/><Field label="Data de nascimento" name="birth_date" type="date"/><div className="space-y-2"><Label>Sexo</Label><Select name="sex" defaultValue="not_informed"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="female">Feminino</SelectItem><SelectItem value="male">Masculino</SelectItem><SelectItem value="other">Outro</SelectItem><SelectItem value="not_informed">Não informado</SelectItem></SelectContent></Select></div><Field label="Função" name="job_title"/><Field label="Data de admissão" name="admission_date" type="date"/><Field label="Posto de trabalho" name="workplace"/></div>{error&&<p className="text-sm text-destructive">{error}</p>}</DialogFrame>}
function ExamDialog({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:user}=await supabase.auth.getUser();const {error:saveError}=await supabase.from("exams").insert({category:String(f.get("category")) as "clinical"|"complementary",name_pt:String(f.get("name_pt")),name_en:String(f.get("name_en")),duration_minutes:Number(f.get("duration")),created_by:user.user?.id??null});if(saveError)setError(saveError.message);else onSaved();}return <DialogFrame open={open} onClose={onClose} onSubmit={submit} title="Novo exame" description="Adicione o nome nos dois idiomas."><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Categoria</Label><Select name="category" defaultValue="complementary"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="clinical">Clínico</SelectItem><SelectItem value="complementary">Complementar</SelectItem></SelectContent></Select></div><Field label="Duração (min)" name="duration" type="number" defaultValue="30"/><Field label="Nome em português" name="name_pt"/><Field label="Nome em inglês" name="name_en"/></div>{error&&<p className="text-sm text-destructive">{error}</p>}</DialogFrame>}
function AppointmentDialog({open,onClose,onSaved,employees,exams,profile,companies}:{open:boolean;onClose:()=>void;onSaved:()=>void;employees:Employee[];exams:Exam[];profile:Profile|null;companies:Company[]}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const employee=employees.find(x=>x.id===String(f.get("employee_id")));const companyId=employee?.company_id??profile?.company_id??companies[0]?.id;if(!companyId){setError("Empresa não encontrada.");return;}const starts=new Date(String(f.get("date"))+"T"+String(f.get("time")));const ends=new Date(starts.getTime()+Number(f.get("duration"))*60000);const {data:user}=await supabase.auth.getUser();if(appointmentsConflict(starts,ends)){setError("Horário inválido.");return;}const {data:created,error:saveError}=await supabase.from("appointments").insert({company_id:companyId,employee_id:String(f.get("employee_id")),assessment_type:String(f.get("assessment_type")),starts_at:starts.toISOString(),ends_at:ends.toISOString(),location:String(f.get("location")),notes:String(f.get("notes")),created_by:user.user?.id??"",updated_by:user.user?.id??""}).select("id").single();if(saveError){setError(saveError.message);return;}const selected=String(f.get("exam_id"));if(created&&selected)await supabase.from("appointment_exams").insert({appointment_id:created.id,exam_id:selected});if(created)await supabase.from("appointment_history").insert({appointment_id:created.id,action:"created",new_status:"scheduled",actor_id:user.user?.id??""});onSaved();}function appointmentsConflict(s:Date,e:Date){return e<=s;}
 return <DialogFrame open={open} onClose={onClose} onSubmit={submit} title="Novo agendamento" description="Defina funcionário, avaliação, exame, data e local."><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Funcionário</Label><Select name="employee_id"><SelectTrigger><SelectValue placeholder="Selecionar"/></SelectTrigger><SelectContent>{employees.map(e=><SelectItem key={e.id} value={e.id}>{e.full_name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Tipo ocupacional</Label><Select name="assessment_type" defaultValue="admission"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="admission">Admissional</SelectItem><SelectItem value="periodic">Periódico</SelectItem><SelectItem value="return_to_work">Retorno ao trabalho</SelectItem><SelectItem value="risk_change">Mudança de risco</SelectItem><SelectItem value="dismissal">Demissional</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Exame</Label><Select name="exam_id"><SelectTrigger><SelectValue placeholder="Selecionar"/></SelectTrigger><SelectContent>{exams.filter(x=>x.is_active).map(x=><SelectItem key={x.id} value={x.id}>{x.name_pt}</SelectItem>)}</SelectContent></Select></div><Field label="Duração (min)" name="duration" type="number" defaultValue="30"/><Field label="Data" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><Field label="Horário" name="time" type="time" defaultValue="09:00"/><Field label="Local" name="location"/><div className="space-y-2 sm:col-span-2"><Label htmlFor="notes">Observações</Label><Textarea id="notes" name="notes" maxLength={2000}/></div></div>{error&&<p className="text-sm text-destructive">{error}</p>}</DialogFrame>}
function JoinDialog({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error:joinError}=await supabase.rpc("join_company_with_code",{_plain_code:String(f.get("code"))});if(joinError)setError("Código inválido, expirado ou empresa ainda não aprovada.");else onSaved();}return <DialogFrame open={open} onClose={onClose} onSubmit={submit} title="Vincular à empresa" description="Insira o código de acesso fornecido pelo administrador."><Field label="Código da empresa" name="code"/>{error&&<p className="text-sm text-destructive">{error}</p>}</DialogFrame>}
function formatCnpj(v:string){return v.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/, "$1.$2.$3/$4-$5")}
function formatCpf(v:string){return v.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/, "$1.$2.$3-$4")}